nav_msgs/Path path
---

# Termination code by the server
uint8  server_code
string server_msg

# Possible server codes:
uint8 ARRIVED        = 20
uint8 STOPPED        = 21
uint8 INVALID_PATH   = 22
uint8 TF_ERROR       = 23
uint8 PAT_EXCEEDED   = 24
uint8 MAX_RETRIES    = 25
uint8 INTERNAL_ERROR = 26
uint8 OSCILLATION    = 27

# Termination code by the plugin, can be useful if no success
# with controlling; plugin code is defined by the local planner
uint8  plugin_code
string plugin_msg

# Possible predefined plugin codes:
uint8 DO_NOT_APPLY   = 255
uint8 COLLISION      = 1
uint8 MISSED_GOAL    = 2
uint8 MISSED_PATH    = 3
uint8 BLOCKED_PATH   = 4

geometry_msgs/PoseStamped  pose
float32 dist_to_goal
float32 angle_to_goal
---

float32 dist_to_goal
float32 angle_to_goal
geometry_msgs/PoseStamped  pose
geometry_msgs/TwistStamped twist
