nav_msgs/Path path

# Applicable local planner plugins. MBF will try them in sequence until one succeeds
# Defaults to local_planners parameter
string[] usable_plugins

---

# Predefined success codes:
uint8 SUCCESS        = 0
# 1..9 are reserved as plugin specific non-error results

# Predefined error codes:
uint8 NO_VALID_CMD   = 60
uint8 CANCELED       = 61
uint8 PAT_EXCEEDED   = 62
uint8 COLLISION      = 63
uint8 OSCILLATION    = 64
uint8 ROBOT_STUCK    = 65
uint8 MISSED_GOAL    = 66
uint8 MISSED_PATH    = 67
uint8 BLOCKED_PATH   = 68
uint8 INVALID_PATH   = 69
uint8 INTERNAL_ERROR = 70
# 71..79 are reserved as plugin specific errors


uint8 return_value
string used_plugin

geometry_msgs/PoseStamped  final_pose
float32 dist_to_goal
float32 angle_to_goal

---

float32 dist_to_goal
float32 angle_to_goal
geometry_msgs/PoseStamped  current_pose
geometry_msgs/TwistStamped current_twist
