# Get a plan from start_pose or current position to the target pose

# Use start_pose or current position as the beginning of the plan
bool use_start_pose

# The start pose for the plan; optional, used if use_start_pose is true
geometry_msgs/PoseStamped start_pose

# The pose to achieve with the plan
geometry_msgs/PoseStamped target_pose

# Intermediate poses the plan should pass by
geometry_msgs/PoseStamped[] waypoints

# If the goal or a waypoint is obstructed, how many meters the
# planner can relax the constraint in x and y before failing
float32 tolerance

---
# Termination code by the server
uint8  server_code
string server_msg

# Possible server codes:
uint8 FOUND_PATH     = 10
uint8 EMPTY_PATH     = 11
uint8 NO_PATH_FOUND  = 12
uint8 CANCELED       = 13
uint8 STOPPED        = 14
uint8 PAT_EXCEEDED   = 15
uint8 MAX_RETRIES    = 16
uint8 TF_ERROR       = 17
uint8 INTERNAL_ERROR = 18

# Termination code by the plugin, can be useful if no success
# with planning; plugin code is defined by the global planner
uint8  plugin_code
string plugin_msg

# Possible predefined plugin codes
uint8 DO_NOT_APPLY     = 255
uint8 START_BLOCKED    = 1
uint8 GOAL_BLOCKED     = 2
uint8 WAYPOINT_BLOCKED = 3
uint8 DOOR_CLOSED      = 4
uint8 DYNAMIC_OBSTACLE = 5

nav_msgs/Path path
---
