# Get a path from start_pose or current position to the target pose

# Use start_pose or current position as the beginning of the path
bool use_start_pose

# The start pose for the path; optional, used if use_start_pose is true
geometry_msgs/PoseStamped start_pose

# The pose to achieve with the path
geometry_msgs/PoseStamped target_pose

# Intermediate poses the path should pass by
geometry_msgs/PoseStamped[] waypoints

# If a waypoint is obstructed, how many meters the plath can pass away of it before failing
# Defaults to goal_tolerance. If only one value is provided, it is used for all the waypoints
float64[] waypoints_tolerance

# If the goal is obstructed, how many meters the planner can relax the constraint in x and y before failing
float64 goal_tolerance

# Applicable global planner plugins. MBF will try them in sequence until one succeeds
# Defaults to global_planners parameter
string[] usable_plugins

---

# Predefined success codes:
uint8 SUCCESS         = 0
# 1..9 are reserved as plugin specific non-error results

# Possible server codes:
uint8 FAILURE         = 50  # Unspecified failure, only used for old, non-mfb_core based plugins
uint8 CANCELED        = 51
uint8 INVALID_START   = 52
uint8 INVALID_GOAL    = 53
uint8 NO_PATH_FOUND   = 54
uint8 PAT_EXCEEDED    = 55
uint8 EMPTY_PATH      = 56
uint8 TF_ERROR        = 57
uint8 NOT_INITIALIZED = 58
uint8 INVALID_PLUGIN  = 59
uint8 INTERNAL_ERROR  = 60
# 71..99 are reserved as plugin specific errors

uint32 outcome
string message
string used_plugin

nav_msgs/Path path

---
