string behavior

---

# Predefined success codes:
uint8 SUCCESS        = 0

# Possible server codes:
uint8 FAILED         = 80
uint8 CANCELED       = 81
uint8 PAT_EXCEEDED   = 82
uint8 INVALID_NAME   = 83
uint8 INTERNAL_ERROR = 84
# 91..99 are reserved as plugin specific errors


uint8 return_value

---
