string behavior

---

# Predefined success codes:
uint8 SUCCESS        = 0

# Possible server codes:
uint8 FAILED         = 150
uint8 CANCELED       = 151
uint8 PAT_EXCEEDED   = 152
uint8 INVALID_NAME   = 153
uint8 INTERNAL_ERROR = 154
# 171..199 are reserved as plugin specific errors


uint8 return_value

---
