# Get a path from start_pose or current position to the target pose

# Use start_pose or current position as the beginning of the path
bool use_start_pose

# The start pose for the path; optional, used if use_start_pose is true
geometry_msgs/PoseStamped start_pose

# The pose to achieve with the path
geometry_msgs/PoseStamped target_pose

# If the goal is obstructed, how many meters the planner can relax the constraint in x and y before failing
float64 tolerance

# Planner to use; defaults to the first one specified on "planners" parameter
string planner

---

# Predefined success codes:
uint8 SUCCESS         = 0
# 1..9 are reserved as plugin specific non-error results

# Possible error codes:
uint8 FAILURE         = 50  # Unspecified failure, only used for old, non-mfb_core based plugins
uint8 CANCELED        = 51  # The action has been canceled by a action client
uint8 INVALID_START   = 52  #
uint8 INVALID_GOAL    = 53
uint8 NO_PATH_FOUND   = 54
uint8 PAT_EXCEEDED    = 55
uint8 EMPTY_PATH      = 56
uint8 TF_ERROR        = 57
uint8 NOT_INITIALIZED = 58
uint8 INVALID_PLUGIN  = 59
uint8 INTERNAL_ERROR  = 60
uint8 STOPPED         = 61  # The planner execution has been stopped rigorously, e.g. Move Base Flex has been shut down.
# 71..99 are reserved as plugin specific errors

uint32 outcome
string message

nav_msgs/Path path

float64 cost

---
