uint8                     LOCAL_COSTMAP  = 1
uint8                     GLOBAL_COSTMAP = 2

geometry_msgs/PoseStamped pose              # the pose to be checked after transforming to costmap frame
float32                   safety_dist       # minimum distance allowed to the closest obstacle
uint8                     costmap           # costmap in which to check the pose
bool                      current_pose      # check current robot pose instead (ignores pose field)
 ---
bool                      colliding         # is the pose closer than safety_dist to a costmap obstacle?
float32                   cost              # cost of the highest-cost cell within the footprint padded
                                            # by safety_dist (negative if in collistion)