name: Format Check CI

on: pull_request

jobs:
  clang_format_check:
    name: clang format check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: the check
        run: sh ./run-style-check-diff.sh
